name: willutil
channels:
 - conda-forge
dependencies:
 - python
 - xarray
 - netcdf4
 - numpy
 - biopython
 - numba
 - tqdm
 - yapf
 - pytest
 - ipython
 - pandas
 - pip
 - deferred-import
 - clang-format
 - pip:
   - pytest-sugar
   - cppimport
