name: willutil
channels:
 - conda-forge
 # - schrodinger
dependencies:
 - python
 - xarray
 - netcdf4
 - numpy
 - biopython
 - numba
 - tqdm
 - yapf
 - pytest
 - ipython
 - pandas
 - pip
 - deferred-import
 - clang-format
 # - pymol-bundle
 - pip:
   - pytest-sugar
   - cppimport
