name: willutil_pymol
channels:
 - conda-forge
 - schrodinger
 - default
dependencies:
 - python
 - pymol-bundle
 - xarray
 - netcdf4
 - numpy
 - numba
 - tqdm
 - yapf
 - pytest
 - ipython
 - pandas
 - clang-format
 - pip
 - pip:
   - pytest-sugar
   - pytest-xdist
   - pytest-parallel   
   - pytest-repeat      
   - cppimport
   - deferred-import