#!/usr/bin/env python

import argparse
import willutil as wu

p = argparse.ArgumentParser()
p.add_argument('files', nargs='*')
p.add_argument("--only_changes", action='store_true', default=False)
p.add_argument("--align_through_comments", action='store_false', default=True)
p.add_argument("--check_with_yapf", action='store_false', default=True)
kw = wu.Bunch(p.parse_args())

def main():
    import sys
    if kw.files:
        for f in kw.files:
            wu.format.align_code_file(
                f,
                inplace=True,
                yapf=True,
                **kw,
            )
    else:
        wu.format.align_code_file(
            None,
            inplace=True,
            yapf=True,
            **kw,
        )

if __name__ == '__main__':
    main()
